services:
  webserver:
    image: nodeserver:1
    ports:
      - 8080:8080
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 3

  nginx:
    image: nginx:1
    ports:
      - 80:80
    depends_on:
      - webserver

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}